=== theopenlane/policytemplates/standards/jsonschema/standards.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema#",
    "$id": "https://github.com/theopenlane/policytemplates/standards",
    "title": "Standards for audit compliance",
    "$defs": {
        "Control": {
            "properties":{
                "ref_code": {
                    "type": "string",
                    "description": "A unique identifier for the control, sometimes referred to as a control number.",
                    "minLength": 1
                },
                "name": {
                    "type": "string",
                    "description": "The name of the control."
                },
                "description": {
                    "type": "string",
                    "description": "A brief description of the control."
                },
                "category": {
                    "type": "string",
                    "description": "The category of the control.",
                    "minLength": 1
                },
                "subcategory": {
                    "type": "string",
                    "description": "The subcategory of the control."
                },
                "metadata": {
                    "type": "object",
                    "items": {
                        "$ref": "#/$defs/Control"
                    },
                    "description": "Additional information about the control which is unique per standard."
                },
                "dti": {
                    "enum": ["easy", "medium", "difficult"],
                    "description": "The difficult to implement rating of the control."
                },
                "dtc": {
                    "enum": ["easy", "medium", "difficult"],
                    "description": "The difficult to collect rating of the control."
                },
                "sub_controls": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/Control"
                    }
                }
            },
            "required": [
                "ref_code",
                "category"
            ]
        },
        "Metadata": {
            "properties": {
                "references": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "points_of_focus": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        }
    },
    "properties": {
      "name": {
        "type": "string",
        "description": "The name of the standard.",
        "minLength": 1
      },
      "version": {
        "type": "string",
        "description": "The version of the standard",
        "minLength": 1
      },
      "web_link": {
        "type": "string",
        "description": "A URL to the standard's documentation."
      },
      "controls": {
        "type": "array",
        "description": "A list of controls that are part of the standard.",
        "items": {
            "$ref": "#/$defs/Control"
        },
        "contains": {
            "minLength": 1
        }
    }
  },
  "required": [
    "name",
    "version",
    "controls"
  ]
}

=== theopenlane/policytemplates/templates/standards/soc2-2022.json
{
    "name": "SOC 2",
    "version": "2017 - with revised points of focus 2022",
    "web_link": "https://www.aicpa-cima.com/resources/download/2017-trust-services-criteria-with-revised-points-of-focus-2022",
    "controls": [
        {
            "description": "The board of directors demonstrates independence from management and exercises oversight of the development and performance of internal control. (COSO Principle 2)",
            "ref_code": "CC1.2",
            "category": "Security",
            "subcategory": "Control Environment",
            "metadata": {
                "points_of_focus": [
                    "Establishes Oversight Responsibilities: The board of directors identifies and accepts its oversight responsibilities in relation to established requirements and expectations.",
                    "Applies Relevant Expertise: The board of directors defines, maintains, and periodically evaluates the skills and expertise needed among its members to enable them to ask probing questions of senior management and take commensurate action.\n– Operates Independently: The board of directors has sufficient members who are independent from management and objective in evaluations and decision making.",
                    "Supplements Board Expertise: The board of directors supplements its expertise relevant to security, availability, processing integrity, confidentiality, and privacy, as needed, through the use of a subcommittee or consultants."
                ]
            }
        },
        {
            "description": "Management establishes, with board oversight, structures, reporting lines, and appropriate authorities and responsibilities in the pursuit of objectives. (COSO Principle 3)",
            "ref_code": "CC1.3",
            "category": "Security",
            "subcategory": "Control Environment",
            "metadata": {
                "points_of_focus": [
                    "Considers All Structures of the Entity: Management and the board of directors consider the multiple structures used (including operating units, legal entities, geographic distribution, and outsourced service providers) to support the achievement of objectives.",
                    "Establishes Reporting Lines: Management designs and evaluates lines of reporting for each entity structure to enable execution of authorities and responsibilities and flow of information to manage the activities of the entity.",
                    "Defines, Assigns, and Limits Authorities and Responsibilities: Management and the board of directors delegate authority, define responsibilities, and use appropriate processes and technology to assign responsibility and segregate duties as necessary at the various levels of the organization.",
                    "Addresses Specific Requirements When Defining Authorities and Responsibilities: Management and the board of directors consider requirements relevant to security, availability, processing integrity, confidentiality, and privacy when defining authorities and responsibilities.",
                    "Considers Interactions With External Parties When Establishing Structures, Reporting Lines, Authorities, and Responsibilities: Management and the board of directors consider the need for the entity to interact with and monitor the activities of external parties when establishing structures, reporting lines, authorities, and responsibilities."
                ]
            }
        },
        {
            "description": "The entity demonstrates a commitment to attract, develop, and retain competent individuals in alignment with objectives. (COSO Principle 4)",
            "ref_code": "CC1.4",
            "category": "Security",
            "subcategory": "Control Environment",
            "metadata": {
                "points_of_focus": [
                    "Establishes Policies and Practices: Policies and practices reflect expectations of competence necessary to support the achievement of objectives.",
                    "Evaluates Competence and Addresses Shortcomings: The board of directors and management evaluate competence across the entity and in outsourced service providers in relation to established policies and practices and act as necessary to address shortcomings.",
                    "Attracts, Develops, and Retains Individuals: The entity provides the mentoring and training needed to attract, develop, and retain sufficient and competent personnel and outsourced service providers to support the achievement of objectives.",
                    "Plans and Prepares for Succession: Senior management and the board of directors develop contingency plans for assignments of responsibility important for internal control.",
                    "Considers the Background of Individuals: The entity considers the background of potential and existing personnel, contractors, and vendor employees when determining whether to employ and retain the individuals.",
                    "Considers the Technical Competency of Individuals: The entity considers the technical competency of potential and existing personnel, contractors, and vendor employees when determining whether to employ and retain the individuals.",
                    "Provides Training to Maintain Technical Competencies: The entity provides training programs, including continuing education and training, to ensure skill sets and technical competency of existing personnel, contractors, and vendor employees are developed and maintained."
                ]
            }
        },
        {
            "description": "The entity holds individuals accountable for their internal control responsibilities in the pursuit of objectives. (COSO Principle 5)",
            "ref_code": "CC1.5",
            "category": "Security",
            "subcategory": "Control Environment",
            "metadata": {
                "points_of_focus": [
                    "Enforces Accountability Through Structures, Authorities, and Responsibilities: Management and the board of directors establish the mechanisms to communicate and hold individuals accountable for performance of internal control responsibilities across the entity and implement corrective action as necessary.",
                    "Establishes Performance Measures, Incentives, and Rewards: Management and the board of directors establish performance measures, incentives, and other rewards appropriate for responsibilities at all levels of the entity, reflecting appropriate dimensions of performance and expected standards of conduct, and considering the achievement of both short-term and longer-term objectives.",
                    "Evaluates Performance Measures, Incentives, and Rewards for Ongoing Relevance: Management and the board of directors align incentives and rewards with the fulfillment of internal control responsibilities in the achievement of objectives.",
                    "Considers Excessive Pressures: Management and the board of directors evaluate and adjust pressures associated with the achievement of objectives as they assign responsibilities, develop performance measures, and evaluate performance.",
                    "Evaluates Performance and Rewards or Disciplines Individuals: Management and the board of directors evaluate performance of internal control responsibilities, including adherence to standards of conduct and expected levels of competence, and provide rewards or exercise disciplinary action, as appropriate.",
                    "Takes Disciplinary Actions - A sanctions process is defined, and applied as needed, when an employee violates the entity�s privacy policies or when an employee�s negligent behavior causes a privacy incident."
                ]
            }
        },
        {
            "description": "The entity obtains or generates and uses relevant, quality information to support the functioning of internal control. (COSO Principle 13)",
            "ref_code": "CC2.1",
            "category": "Security",
            "subcategory": "Communication and Information",
            "metadata": {
                "points_of_focus": [
                    "Captures Internal and External Sources of Data: Information systems capture internal and external sources of data.",
                    "Processes Relevant Data Into Information: Information systems process and transform relevant data into information.",
                    "Maintains Quality Throughout Processing: Information systems produce information that is timely, current, accurate, complete, accessible, protected, verifiable, and retained. Information is reviewed to assess its relevance in supporting the internal control components.",
                    "Documents Data Flow - The entity documents and uses internal and external information and data flows to support the design and operation of controls.",
                    "Manages Assets - The entity identifies, documents, and maintains records of system components such as infrastructure, software, and other information assets. Information assets include physical endpoint devices and systems, virtual systems, data and data flows, external information systems, and organizational roles.",
                    "Classifies Information - The entity classifies information by its relevant characteristics (for example, personally identifiable information, confidential customer information, and intellectual property) to support identification of threats to the information and the design and operation of controls.",
                    "Uses Information That Is Complete and Accurate - The entity uses information and reports that are complete, accurate, current, and valid in the operation of controls.",
