=== theopenlane/policytemplates/schema/jsonschema/frameworks.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://theopenlane.io/draft-0/framework",
  "$ref": "#/$defs/Framework",
  "$defs": {
    "Control": {
      "properties": {
        "name": {
          "type": "string",
          "description": "name of the control"
        },
        "description": {
          "type": "string",
          "description": "short description of the control"
        },
        "ref_code": {
          "type": "string",
          "minLength": 1,
          "description": "unique identifier for the control in the framework; sometimes referred to as a control number",
          "examples": [
            "CC1.1",
            "AC-2"
          ]
        },
        "category": {
          "type": "string",
          "minLength": 1,
          "description": "category of the control",
          "examples": [
            "Security",
            "Availability"
          ]
        },
        "subcategory": {
          "type": "string",
          "description": "subcategory of the control",
          "examples": [
            "System Operation",
            "Control Environment"
          ]
        },
        "sub_controls": {
          "items": {
            "$ref": "#/$defs/Control"
          },
          "type": "array",
          "description": "sub-controls of the control if applicable"
        },
        "dti": {
          "type": "string",
          "enum": [
            "easy",
            "medium",
            "difficult"
          ],
          "description": "difficulty to implement rating of the control"
        },
        "dtc": {
          "type": "string",
          "enum": [
            "easy",
            "medium",
            "difficult"
          ],
          "description": "difficulty to collect evidence rating of the control"
        },
        "guidance": {
          "type": "string",
          "description": "guidance or suggested steps for implementing the control"
        },
        "metadata": {
          "oneOf": [
            {
              "type": "object"
            },
            {
              "type": "array"
            }
          ],
          "description": "metadata for the control; unique to the framework"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "ref_code",
        "category"
      ]
    },
    "Framework": {
      "properties": {
        "name": {
          "type": "string",
          "minLength": 1,
          "description": "name of the framework",
          "examples": [
            "SOC 2",
            "NIST CSF"
          ]
        },
        "framework": {
          "type": "string",
          "minLength": 1,
          "description": "shortname (slug) of the framework",
          "examples": [
            "soc2",
            "nist_csf"
          ]
        },
        "version": {
          "type": "string",
          "minLength": 1,
          "description": "version of the framework",
          "examples": [
            "2017",
            "1.1"
          ]
        },
        "web_link": {
          "type": "string",
          "description": "link to the documentation for the controls"
        },
        "controls": {
          "items": {
            "$ref": "#/$defs/Control"
          },
          "type": "array",
          "description": "a list of controls for the framework"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "name",
        "framework",
        "version",
        "controls"
      ]
    }
  }
}

=== theopenlane/policytemplates/templates/frameworks/iso-27001.json
{
    "name": "ISO 27001",
    "framework": "iso27001",
    "version": "2022",
    "web_link": "https://www.iso.org/standard/27001",
    "controls": [
        {
            "name": "Organization Controls",
            "description": "Information security policies",
            "ref_code": "A.5",
            "category": "Organization Controls",
            "sub_controls": [
                {
                    "name": "Policies for information security",
                    "description": "Information security policy and topic-specific policies shall be defined, approved by management, published, communicated to and acknowledged by relevant personnel and relevant interested parties, and reviewed at planned intervals and if significant changes occur.",
                    "ref_code": "A.5.1",
                    "category": "Organization Controls",
                    "metadata": {}
                },
                {
                    "name": "Information security roles and responsibilities",
                    "description": "Information security roles and responsibilities shall be defined and allocated according to the organization needs.",
                    "ref_code": "A.5.2",
                    "category": "Organization Controls",
                    "metadata": {}
                },
                {
                    "name": "Segregation of duties",
                    "description": "Conflicting duties and conflicting areas of responsibility shall be segregated.",
                    "ref_code": "A.5.3",
                    "category": "Organization Controls",
                    "metadata": {}
                },
                {
                    "name": "Management responsibilities",
                    "description": "Management shall require all personnel to apply information security in accordance with the established information security policy, topic-specific policies and procedures of the organization.",
                    "ref_code": "A.5.4",
                    "category": "Organization Controls",
                    "metadata": {}
                },
                {
                    "name": " Contact with authorities",
                    "description": "The organization shall establish and maintain contact with relevant authorities.",
                    "ref_code": "A.5.5",
                    "category": "Organization Controls",
                    "metadata": {}
                },
                {
                    "name": " Contact with special interest groups",
                    "description": "The organization shall establish and maintain contact with special interest groups or other specialist security forums and professional associations.",
                    "ref_code": "A.5.6",
                    "category": "Organization Controls",
                    "metadata": {}
                },
                {
                    "name": "Threat intelligence",
                    "description": "Information relating to information security threats shall be collected and analysed to produce threat intelligence.",
                    "ref_code": "A.5.7",
                    "category": "Organization Controls",
                    "metadata": {}
                },
                {
                    "name": "Information security in project management",
                    "description": "Information security shall be integrated into project management.",
                    "ref_code": "A.5.8",
                    "category": "Organization Controls",
                    "metadata": {}
                },
                {
                    "name": "Information security in project management",
                    "description": "An inventory of information and other associated assets, including owners, shall be developed and maintained.",
                    "ref_code": "A.5.9",
                    "category": "Organization Controls",
                    "metadata": {}
                },
                {
                    "name": "Acceptable use of information and other associated assets",
                    "description": "Rules for the acceptable use and procedures for handling information and other associated assets shall be identified, documented and implemented.",
                    "ref_code": "A.5.10",
                    "category": "Organization Controls",
                    "metadata": {}
                },
                {
                    "name": "Acceptable use of information and other associated assets",
                    "description": "Rules for the acceptable use and procedures for handling information and other associated assets shall be identified, documented and implemented.",
                    "ref_code": "A.5.11",
                    "category": "Organization Controls",
                    "metadata": {}
                },
                {
                    "name": "Classification of information",
                    "description": "Information shall be classified according to the information security needs of the organization based on confidentiality, integrity, availability and relevant interested party requirements.",
                    "ref_code": "A.5.12",
                    "category": "Organization Controls",
                    "metadata": {}
                },
                {
                    "name": "Labelling of information",
                    "description": "An appropriate set of procedures for information labelling shall be developed and implemented in accordance with the information classification scheme adopted by the organization.",
                    "ref_code": "A.5.13",
                    "category": "Organization Controls",
                    "metadata": {}
                },
                {
                    "name": "Information transfer",
                    "description": "Information transfer rules, procedures, or agreements shall be in place for all types of transfer facilities within the organization and between the organization and other parties.",
                    "ref_code": "A.5.14",
                    "category": "Organization Controls",
                    "metadata": {}
                },
                {
                    "name": "Access control",
                    "description": "Rules to control physical and logical access to information and other associated assets shall be established and implemented based on business and information security requirements.",
                    "ref_code": "A.5.15",
                    "category": "Organization Controls",
                    "metadata": {}
                },
                {
                    "name": "Identity management",
                    "description": "The full life cycle of identities shall be managed.",
                    "ref_code": "A.5.16",
                    "category": "Organization Controls",
                    "metadata": {}
                },
                {
                    "name": "Authentication information",
                    "description": "Allocation and management of authentication information shall be controlled by a management process, including advising personnel on appropriate handling of authentication information.",
                    "ref_code": "A.5.17",
                    "category": "Organization Controls",
                    "metadata": {}
                },
                {
                    "name": "Access rights",
                    "description": "Access rights to information and other associated assets shall be provisioned, reviewed, modified and removed in accordance with the organization’s topic-specific policy on and rules for access control.",
                    "ref_code": "A.5.18",
                    "category": "Organization Controls",
                    "metadata": {}
                },
                {
                    "name": "Information security in supplier relationships",
                    "description": "Processes and procedures shall be defined and implemented to manage the information security risks associated with the use of supplier’s products or services.",
                    "ref_code": "A.5.19",
                    "category": "Organization Controls",
                    "metadata": {}
                },
                {
                    "name": "Addressing information security within supplier agreements",
                    "description": "Relevant information security requirements shall be established and agreed with each supplier based on the type of supplier relationship.",
                    "ref_code": "A.5.20",
                    "category": "Organization Controls",
                    "metadata": {}
                },
                {
                    "name": "Managing information security in the information and communication technology (ICT) supply chain",
                    "description": "Processes and procedures shall be defined and implemented to manage the information security risks associated with the ICT products and services supply chain.",
                    "ref_code": "A.5.21",
                    "category": "Organization Controls",
                    "metadata": {}
                },
                {
                    "name": "Monitoring, review and change management of supplier services",
                    "description": "The organization shall regularly monitor, review, evaluate and manage change in supplier information security practices and service delivery.",
                    "ref_code": "A.5.22",
                    "category": "Organization Controls",
                    "metadata": {}
                },
                {
                    "name": "Information security for use of cloud services",
